name: harubee
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  dart_eval: ^0.8.2
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 앱에서 사용할 이미지 리소스
  assets:
    - lib/design_system/images/

  # 앱에서 사용할 폰트
  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/design_system/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: lib/design_system/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/design_system/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/design_system/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/design_system/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/design_system/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/design_system/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/design_system/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/design_system/fonts/Pretendard-Black.ttf
          weight: 900